lspcontainers/lspcontainers.nvim

README.md
lua/lspcontainers/init.lua

This provides the initial implementation for `lspcontainers.nvim` and basic documentation.

#1: Initial Implementation

---

README.md

It's a simple first PR. Found a typo in the readme when trying out the plugin.

docs(readme): fix typo in lspconfig setup

---

lua/lspcontainers/init.lua

Pretty simple stuff at the moment. Spent a lot of time tinkering with it on windows (non WSL2), the workdir volume mounts so not work quite right there. I would like to experiment more with windows support outside of WSL2, but this works fine in WSL2 right now.
One issue I've run into is that if you're outside of your go modules directory and open the file it's going to use the cwd you're in, not where the file is located, so gopls will throw errors. I believe that's just something that will be handled as the system matures naturally though.

Initial support for the Go language server (gopls)

---

README.md
lua/lspcontainers/init.lua

Adds newly implemented LSPs from the following PRs:
- https://github.com/lspcontainers/dockerfiles/pull/5
- https://github.com/lspcontainers/dockerfiles/pull/6

#8: Adds newly implemented LSPs

---

README.md
lua/lspcontainers/init.lua

#10: Add pyright LSP

---

.github/workflows/test.yml
.gitignore
lua/lspcontainers/init.lua
scripts/test.lua
scripts/test.sh

Test the list of languages matches lspconfig names

---

README.md
lua/lspcontainers/init.lua

* adding jsonls
* adding html
* adding vuels

Adding new ls

---

lua/lspcontainers/init.lua

Depends on lspcontainers/dockerfiles#42

bump svelteserver version

---

lua/lspcontainers/init.lua

It depends on pr https://github.com/lspcontainers/dockerfiles/pull/40 to be merged

feature: bumping terraformls to 0.19.1

---

lua/lspcontainers/init.lua

Simply use it as a fallback in `command`.

Deduplicate definition of default_cmd

---

README.md

See https://github.com/johnsoncodehk/volar/issues/706 and https://github.com/lspcontainers/dockerfiles/issues/53

Add an explanation on processId being problematic

---

scripts/test.lua

fix(test.lua)

---

lua/lspcontainers/init.lua

fix(gopls): gopath, volumes, write access

---

lua/lspcontainers/init.lua

Adds script to do dynamic user changing when starting `gopls`.

feat(gopls): add support for dynamic user retrival

---

.gitattributes
README.md
lua/lspcontainers/init.lua

Add: Mount a docker volume or a host path (workdir)
Update: Documentation for this feature.

Feature: Use docker volumes

---

README.md
lua/lspcontainers/init.lua

Adds support for `graphql-lsp` configurations and documentation.

Add graphql-lsp

---

lua/lspcontainers/init.lua

Make images_pull runtime parametrised

---

lua/lspcontainers/init.lua

Some more context to this can be found in #70.
Closes #70

feat(selinux): add selinux labels to volumes for shared access

---

README.md
lua/lspcontainers/init.lua

Add Prisma Language Server

---

lua/lspcontainers/init.lua

I'm hesitant on whether this should be inside the `setup` method or not.

Use lua to define custom commands

---

lua/lspcontainers/init.lua

Fixes the networking part of #68

 fix(gopls): networking mode depending on runtime

---

README.md

This updates the README.md to improve documentation around using `utils` with `lspcontainers`.

Updated util usage examples

---

README.md
doc/lspcontainers.txt
init.lua
lua/lspcontainers/init.lua

as per https://github.com/neovim/nvim-lspconfig/pull/2439

Rename "sumneko_lua" to "lua_ls"

---

README.md
init.lua
lua/lspcontainers/init.lua

Plugin side of https://github.com/lspcontainers/dockerfiles/pull/90

add denols

---

README.md
init.lua
lua/lspcontainers/init.lua

Container PR here - https://github.com/lspcontainers/dockerfiles/pull/96

Add the XML LSP - lemminx
